<?php
acf_add_local_field_group(array(
	'key' => 'group_ammer_front_page',
	'title' => 'Front Page Settings',
	'fields' => array(
		// HERO SECTION
		array(
			'key' => 'field_hero_tab',
			'label' => 'Hero Section',
			'name' => '',
			'type' => 'tab',
			'placement' => 'top',
		),
		array(
			'key' => 'field_hero_title',
			'label' => 'Hero Title',
			'name' => 'hero_title',
			'type' => 'text',
			'default_value' => 'ابتسامتك تبدأ من هنا',
		),
		array(
			'key' => 'field_hero_subtitle',
			'label' => 'Hero Subtitle',
			'name' => 'hero_subtitle',
			'type' => 'textarea',
			'default_value' => 'نقدم لك أحدث التقنيات في عالم طب وتجميل الأسنان لنمنحك الابتسامة التي تستحقها.',
		),
		array(
			'key' => 'field_hero_image',
			'label' => 'Hero Image',
			'name' => 'hero_image',
			'type' => 'image',
			'return_format' => 'url',
		),
		array(
			'key' => 'field_booking_title',
			'label' => 'Booking Title',
			'name' => 'booking_title',
			'type' => 'text',
			'default_value' => 'احجز موعدك الآن',
		),
        
        // SERVICES SECTION
        array(
			'key' => 'field_services_tab',
			'label' => 'Services Section',
			'name' => '',
			'type' => 'tab',
			'placement' => 'top',
		),
        array(
			'key' => 'field_services_title',
			'label' => 'Services Title',
			'name' => 'services_title',
			'type' => 'text',
			'default_value' => 'خدماتنا المميزة',
		),
        array(
			'key' => 'field_services_subtitle',
			'label' => 'Services Subtitle',
			'name' => 'services_subtitle',
			'type' => 'textarea',
			'default_value' => 'نقدم مجموعة شاملة من خدمات طب وتجميل الأسنان...',
		),
        array(
            'key' => 'field_service_1_tab',
            'label' => 'Service 1',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_service_1_icon',
            'label' => 'Icon (Image URL)',
            'name' => 'service_1_icon',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_1_title',
            'label' => 'Title',
            'name' => 'service_1_title',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_1_desc',
            'label' => 'Description',
            'name' => 'service_1_desc',
            'type' => 'textarea',
        ),
        array(
            'key' => 'field_service_2_tab',
            'label' => 'Service 2',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_service_2_icon',
            'label' => 'Icon (Image URL)',
            'name' => 'service_2_icon',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_2_title',
            'label' => 'Title',
            'name' => 'service_2_title',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_2_desc',
            'label' => 'Description',
            'name' => 'service_2_desc',
            'type' => 'textarea',
        ),
        array(
            'key' => 'field_service_3_tab',
            'label' => 'Service 3',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_service_3_icon',
            'label' => 'Icon (Image URL)',
            'name' => 'service_3_icon',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_3_title',
            'label' => 'Title',
            'name' => 'service_3_title',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_3_desc',
            'label' => 'Description',
            'name' => 'service_3_desc',
            'type' => 'textarea',
        ),
        array(
            'key' => 'field_service_4_tab',
            'label' => 'Service 4',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_service_4_icon',
            'label' => 'Icon (Image URL)',
            'name' => 'service_4_icon',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_4_title',
            'label' => 'Title',
            'name' => 'service_4_title',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_4_desc',
            'label' => 'Description',
            'name' => 'service_4_desc',
            'type' => 'textarea',
        ),
        array(
            'key' => 'field_service_5_tab',
            'label' => 'Service 5',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_service_5_icon',
            'label' => 'Icon (Image URL)',
            'name' => 'service_5_icon',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_5_title',
            'label' => 'Title',
            'name' => 'service_5_title',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_5_desc',
            'label' => 'Description',
            'name' => 'service_5_desc',
            'type' => 'textarea',
        ),
        array(
            'key' => 'field_service_6_tab',
            'label' => 'Service 6',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_service_6_icon',
            'label' => 'Icon (Image URL)',
            'name' => 'service_6_icon',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_6_title',
            'label' => 'Title',
            'name' => 'service_6_title',
            'type' => 'text',
        ),
        array(
            'key' => 'field_service_6_desc',
            'label' => 'Description',
            'name' => 'service_6_desc',
            'type' => 'textarea',
        ),
		),
        
        // TRUST SECTION
        array(
			'key' => 'field_trust_tab',
			'label' => 'Trust Section',
			'name' => '',
			'type' => 'tab',
			'placement' => 'top',
		),
        array(
			'key' => 'field_trust_title',
			'label' => 'Trust Title',
			'name' => 'trust_title',
			'type' => 'text',
			'default_value' => 'ليش تختار د.عامر الريمي؟',
		),
        array(
			'key' => 'field_trust_desc',
			'label' => 'Trust Description',
			'name' => 'trust_desc',
			'type' => 'textarea',
		),
        array(
			'key' => 'field_trust_image',
			'label' => 'Trust Image',
			'name' => 'trust_image',
			'type' => 'image',
			'return_format' => 'url',
		),
        array(
            'key' => 'field_stat_1_tab',
            'label' => 'Statistic 1',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_stat_1_text',
            'label' => 'Label',
            'name' => 'stat_1_label',
            'type' => 'text',
        ),
        array(
            'key' => 'field_stat_1_num',
            'label' => 'Number/Value',
            'name' => 'stat_1_number',
            'type' => 'text',
        ),
        array(
            'key' => 'field_stat_2_tab',
            'label' => 'Statistic 2',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_stat_2_text',
            'label' => 'Label',
            'name' => 'stat_2_label',
            'type' => 'text',
        ),
        array(
            'key' => 'field_stat_2_num',
            'label' => 'Number/Value',
            'name' => 'stat_2_number',
            'type' => 'text',
        ),
        array(
            'key' => 'field_stat_3_tab',
            'label' => 'Statistic 3',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_stat_3_text',
            'label' => 'Label',
            'name' => 'stat_3_label',
            'type' => 'text',
        ),
        array(
            'key' => 'field_stat_3_num',
            'label' => 'Number/Value',
            'name' => 'stat_3_number',
            'type' => 'text',
        ),
        array(
            'key' => 'field_stat_4_tab',
            'label' => 'Statistic 4',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_stat_4_text',
            'label' => 'Label',
            'name' => 'stat_4_label',
            'type' => 'text',
        ),
        array(
            'key' => 'field_stat_4_num',
            'label' => 'Number/Value',
            'name' => 'stat_4_number',
            'type' => 'text',
        ),
		),
        
        // BEFORE/AFTER SECTION
        array(
			'key' => 'field_ba_tab',
			'label' => 'Before/After Section',
			'name' => '',
			'type' => 'tab',
			'placement' => 'top',
		),
        array(
            'key' => 'field_case_1_tab',
            'label' => 'Case 1',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_case_1_before',
            'label' => 'Before Image URL',
            'name' => 'case_1_before',
            'type' => 'text',
        ),
        array(
            'key' => 'field_case_1_after',
            'label' => 'After Image URL',
            'name' => 'case_1_after',
            'type' => 'text',
        ),
        array(
            'key' => 'field_case_2_tab',
            'label' => 'Case 2',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_case_2_before',
            'label' => 'Before Image URL',
            'name' => 'case_2_before',
            'type' => 'text',
        ),
        array(
            'key' => 'field_case_2_after',
            'label' => 'After Image URL',
            'name' => 'case_2_after',
            'type' => 'text',
        ),
        array(
            'key' => 'field_case_3_tab',
            'label' => 'Case 3',
            'name' => '',
            'type' => 'accordion',
            'open' => 0,
            'multi_expand' => 1,
        ),
        array(
            'key' => 'field_case_3_before',
            'label' => 'Before Image URL',
            'name' => 'case_3_before',
            'type' => 'text',
        ),
        array(
            'key' => 'field_case_3_after',
            'label' => 'After Image URL',
            'name' => 'case_3_after',
            'type' => 'text',
        ),
	),
	'location' => array(
		array(
			array(
				'param' => 'page_template',
				'operator' => '==',
				'value' => 'front-page.php', // Will show on front-page template
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'active' => true,
));
